apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.awsChamberAccountSecretName }}
  annotations:
    "helm.sh/hook": pre-install
type: Opaque
data:
  region: {{ required "AWS Region is required to perform deployment" .Values.aws.region }}
  accessKeyId: {{ required "AWS Access Key ID is required to perform deployment" .Values.aws.accessKeyId }}
  secretAccessKey: {{ required "AWS Secret Access Key is required to perform deployment" .Values.aws.secretAccessKey }}
