apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.awsChamberAccountSecretName }}
  annotations:
    "helm.sh/hook": pre-install
type: Opaque
data:
  region: {{ required "AWS Region is required to perform deployment" .Values.aws.region | b64enc | quote }}
  accessKeyId: {{ required "AWS Access Key ID is required to perform deployment" .Values.aws.accessKeyId | b64enc | quote }}
  secretAccessKey: {{ required "AWS Secret Access Key is required to perform deployment" .Values.aws.secretAccessKey | b64enc | quote }}
  secretChamberPath: {{ required "AWS SSM path that the secrets to be injected can be found at, e.g., `/app/environment`" .Values.botTwitter.secretChamberPath | b64enc | quote }}
