apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.bot.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.bot.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.bot.name }}
    spec:
      {{- if .Values.images.secretName }}
      imagePullSecrets:
      - name: {{ .Values.images.secretName }}
      {{- end }}
      containers:
      - name: {{ .Values.bot.name }}
        image: {{ .Values.repoPrefix }}{{ required "You must specify a deployment image" .Values.bot.deployment.image }}:{{ required "You must specify the version to be deployed" .Values.bot.deployment.tag }}
        imagePullPolicy: {{ .Values.bot.deployment.pullPolicy }}
        env:
        - name: "AWS_REGION"
          valueFrom:
            secretKeyRef:
              name: {{ .Values.awsChamberAccountSecretName }}
              key: "region"
        - name: "AWS_ACCESS_KEY_ID"
          valueFrom:
            secretKeyRef:
              name: {{ .Values.awsChamberAccountSecretName }}
              key: "accessKeyId"
        - name: "AWS_SECRET_ACCESS_KEY"
          valueFrom:
            secretKeyRef:
              name: {{ .Values.awsChamberAccountSecretName }}
              key: "secretAccessKey"
        - name: "SECRET_CHAMBER_PATH"
          valueFrom:
            secretKeyRef:
              name: {{ .Values.awsChamberAccountSecretName }}
              key: "secretChamberPath"
