apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}-ingress
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.class }}
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    {{- if .Values.ingress.isCertManagerActivated }}
    cert-manager.io/cluster-issuer: "cloudflare-issuer"
    {{- end }}
spec:
  {{- if .Values.ingress.tls }}
  tls:
    {{- .Values.ingress.tls | toYaml | nindent 4 }}
  {{- end }}
  rules:
    {{- $frontendName := .Values.frontend.name }}
    {{- range .Values.hosts }}
    - host: {{ required "A host is required for the ingress to work" . }}
      http:
        paths:
        - path: /(.*)
          pathType: Prefix
          backend:
            service:
              name: {{ $frontendName }}-service
              port:
                number: 80
    {{- end }}
