kind: template
load: pipeline-builder.star
data:
  builds:
    # frontend: publish main
    - name: publish-frontend-main
      repository: ghcr.io/sidestream-tech/auction-ui/frontend
      tags:
        - "main"
        - "${DRONE_COMMIT_SHA}"
      labels:
        - key: org.opencontainers.image.source
          value: https://github.com/sidestream-tech/auction-ui
      path_to_dockerfile: frontend/Dockerfile
      path_to_context: ./
      build_args:
        - key: PRODUCTION_DOMAIN
          value_from_secret: auction-ui/staging/production_domain
        - key: INFURA_PROJECT_ID
          value_from_secret: auction-ui/staging/infura_project_id
        - key: CONTACT_EMAIL
          value_from_secret: auction-ui/staging/contact_email
      tags_to_cache_from:
        - "main"
      trigger:
        event:
          - push
        branch:
          - main

    # frontend: publish release
    - name: publish-frontend-release
      tags:
        - "${DRONE_TAG}"
      repository: ghcr.io/sidestream-tech/auction-ui/frontend
      labels:
        - key: org.opencontainers.image.source
          value: https://github.com/sidestream-tech/auction-ui
      path_to_dockerfile: frontend/Dockerfile
      path_to_context: ./
      build_args:
        - key: PRODUCTION_DOMAIN
          value_from_secret: auction-ui/staging/production_domain
        - key: INFURA_PROJECT_ID
          value_from_secret: auction-ui/staging/infura_project_id
        - key: CONTACT_EMAIL
          value_from_secret: auction-ui/staging/contact_email
      tags_to_cache_from:
        - "main"
      trigger:
        event:
          - tag

    # frontend: publish development
    - name: publish-frontend-development
      target: development
      repository: ghcr.io/sidestream-tech/auction-ui/frontend
      tags:
        - "pr-${DRONE_PULL_REQUEST}"
      labels:
        - key: org.opencontainers.image.source
          value: https://github.com/sidestream-tech/auction-ui
      path_to_dockerfile: frontend/Dockerfile
      path_to_context: ./
      build_args:
        - key: PRODUCTION_DOMAIN
          value_from_secret: auction-ui/staging/production_domain
        - key: INFURA_PROJECT_ID
          value_from_secret: auction-ui/staging/infura_project_id
        - key: CONTACT_EMAIL
          value_from_secret: auction-ui/staging/contact_email
      tags_to_cache_from:
        - "main"
      trigger:
        event:
          - pull_request

    # frontend-makerdao: publish release
    - name: publish-frontend-makerdao
      repository: ghcr.io/sidestream-tech/auction-ui/frontend-makerdao
      tags:
        - "${DRONE_TAG}"
      labels:
        - key: org.opencontainers.image.source
          value: https://github.com/sidestream-tech/auction-ui
      path_to_dockerfile: frontend/Dockerfile
      path_to_context: ./
      build_args:
        - key: PRODUCTION_DOMAIN
          value_from_secret: auction-ui/production/production_domain
        - key: INFURA_PROJECT_ID
          value_from_secret: auction-ui/production/infura_project_id
        - key: CONTACT_EMAIL
          value_from_secret: auction-ui/production/contact_email
      tags_to_cache_from:
        - "main"
      trigger:
        event:
          - tag

    # bot-twitter: publish main
    - name: publish-bot-twitter-main
      repository: ghcr.io/sidestream-tech/auction-ui/bot-twitter
      tags:
        - "main"
        - "${DRONE_COMMIT_SHA}"
      labels:
        - key: org.opencontainers.image.source
          value: https://github.com/sidestream-tech/auction-ui
      path_to_dockerfile: bot-twitter/Dockerfile
      path_to_context: ./
      tags_to_cache_from:
        - "main"
      trigger:
        event:
          - push
        branch:
          - main

    # bot-twitter: publish release
    - name: publish-bot-twitter-release
      repository: ghcr.io/sidestream-tech/auction-ui/bot-twitter
      tags:
        - "${DRONE_TAG}"
      labels:
        - key: org.opencontainers.image.source
          value: https://github.com/sidestream-tech/auction-ui
      path_to_dockerfile: bot-twitter/Dockerfile
      path_to_context: ./
      tags_to_cache_from:
        - "main"
      trigger:
        event:
          - tag

    # bot-twitter: publish development
    - name: publish-bot-twitter-development
      target: development
      repository: ghcr.io/sidestream-tech/auction-ui/bot-twitter
      tags:
        - "pr-${DRONE_PULL_REQUEST}"
      labels:
        - key: org.opencontainers.image.source
          value: https://github.com/sidestream-tech/auction-ui
      path_to_dockerfile: bot-twitter/Dockerfile
      path_to_context: ./
      tags_to_cache_from:
        - "main"
      trigger:
        event:
          - pull_request

  in_development_image_pipelines:
    - name: core-lint-build
      type: kubernetes
      depends_on: [publish-frontend-development]
      image: ghcr.io/sidestream-tech/auction-ui/frontend:pr-${DRONE_PULL_REQUEST}
      workdir: /core
      steps_parallel:
        - name: lint
          command: npm run lint
        - name: build
          command: npm run build
      trigger:
        event:
          - pull_request
    - name: frontend-lint-test-build
      type: kubernetes
      depends_on: [publish-frontend-development]
      image: ghcr.io/sidestream-tech/auction-ui/frontend:pr-${DRONE_PULL_REQUEST}
      workdir: /frontend
      steps_parallel:
        - name: lint
          command: npm run lint
        - name: test
          command: npm run test
        - name: build
          command: npm run build
      trigger:
        event:
          - pull_request
    - name: bot-twitter-lint-build
      type: kubernetes
      depends_on: [publish-bot-twitter-development]
      image: ghcr.io/sidestream-tech/auction-ui/bot-twitter:pr-${DRONE_PULL_REQUEST}
      workdir: /bot-twitter
      steps_parallel:
        - name: lint
          command: npm run lint
        - name: build
          command: npm run build
      trigger:
        event:
          - pull_request
