version: '3'

services:

    bot:
        restart: unless-stopped
        environment:
            - AWS_REGION=eu-central-1
            - AWS_ACCESS_KEY_ID
            - AWS_SECRET_ACCESS_KEY
        build:
            context: .
            dockerfile: bot/Dockerfile

    frontend:
        restart: unless-stopped
        expose:
            - 3000
        env_file:
            - './frontend/.env'
        build:
            context: .
            dockerfile: ./frontend/Dockerfile
            environment:
                - INFURA_PROJECT_ID
                - DEMO_MODE
                - PRODUCTION_DOMAIN
                - CONTACT_EMAIL

    reverse-proxy:
        image: nginx:stable-alpine
        ports:
            - '80:80'
        volumes:
            - ./reverse-proxy/production.conf:/etc/nginx/nginx.conf
        depends_on:
            - frontend
