# Credentials to:
# - image repository: Grants read access to repository that containts docker images to be deployed
# - aws ssm: Grants read access to the secret credentials to be injected
#
# Get the filled out file via:
# ```sh
# aws-vault exec YOUR_AWS_USERNAME -- chamber read --quiet auction-ui secrets.yaml | base64 -d > secrets.yaml
# ```
# Substitute `YOUR_AWS_USERNAME` with your authorized username.
#
#
# To store a filled in version file named `secrets.yaml`:
# ```sh
# aws-vault exec YOUR_AWS_USERNAME -- cat secrets.yaml | base64 | chamber write auction-ui secrets.yaml -
# ```

imagesCredentials:
    # Registry domain, something like "ghcr.io"
    registry:
    # Registry username
    username:
    # Registry password
    password:

aws:
  # AWS region where secrets are stored
  region: "eu-central-1"
  # AWS IAM access key id with read rights to `auction-ui/*`
  accessKeyId:
  # AWS IAM secret access key with read rights to `auction-ui/*`
  secretAccessKey:
