# Value overrides for the deployment to the following host:
hosts:
- "auctions.makerdao.network"
- "unified-auctions.makerdao.com"

frontend:
  deployment:
    # the frontend bakes in environment variables that need to be changed for makerdao,
    # so we built a separate image just for that
    image: "frontend-makerdao"

bot:
  secretChamberPath: "auction-ui/auctions.makerdao.network/bot"
