# The `GH_WORKFLOW_TOKEN` of this flow needs the following permissions:
# - admin:org - as project boards are organization wide
# - repo:status, deployment, public_repo
# - project:read 
# `GH_PROJECT_URL` is the URL of the Projectboard being used in the format:
# - https://github.com/orgs/<orgName>/projects/<projectNumber>
name: Add issue to project "SIDESTREAM"

on:
  issues:
    types:
      - opened

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.4.0
        with:
          project-url: ${{ secrets.GH_PROJECT_URL }}
          github-token: ${{ secrets.GH_WORKFLOW_TOKEN }}
